trigger:
- master

jobs:

- job: Build
  pool:
    name: Hosted macOS
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.6'
    inputs:
      versionSpec: 3.6
  
  - script: |
      pip install -r requirements.txt
      ./compile.sh
    displayName: 'Build'
    
  - script: dist/install_simnibs -s --pre-release
      displayName: 'Test'
      
  - script |
      mv dist/* .
      zip -r install_simnibs_macOS.zip install_simnibs
    displayName: 'Prepare distribution'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: macOS-dist'
    inputs:
      PathtoPublish: 'install_simnibs_macOS.zip'
      ArtifactName: 'macOS-dist'

  - task: GithubRelease@0
    displayName: Edit GitHub Release
    inputs: 
      gitHubConnection: guilhermebs # I use my connection because github does not generate OAuth token for organizations
      repositoryName: simnibs/simnibs-installer
      action: edit
      tag: dev
      assets: install_simnibs_macOS.zip
      assetUploadMode: 'replace'
      isDraft: true
