trigger:
- master

jobs:

- job: Build
  pool:
    name: Hosted VS2017
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.6'
    inputs:
      versionSpec: 3.6

  - script: |
      pip install -r requirements.txt
    displayName: 'Install Requirements'

  ## The tests do not work with the windowed version, so first I test without --windowed
  - script: |
      pyinstaller --onefile install_simnibs.py
      dist\install_simnibs.exe -s --pre-release
      rd /Q /S dist
    displayName: 'Test'

  - script: |
      call compile.cmd
      move dist\install_simnibs.exe dist\install_simnibs_windows.exe
    displayName: 'Build'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: win-dist'
    inputs:
      PathtoPublish: dist
      ArtifactName: 'win-dist'

  - task: GithubRelease@0
    displayName: Edit GitHub Release
    inputs: 
      gitHubConnection: guilhermebs # I use my connection because github does not generate OAuth token for organizations
      repositoryName: simnibs/simnibs-installer
      action: edit
      tag: dev
      assets: dist\install_simnibs_windows.exe
      assetUploadMode: 'replace'
      isDraft: true
